apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace-rbac.yaml
- cronjob.yaml
configMapGenerator:
- name: acm-health-check-script
  namespace: acm-health-check
  files:
  - acm-health-check-lite.sh=acm-health-check-lite.sh
generatorOptions:
  disableNameSuffixHash: true
  labels:
    app.kubernetes.io/name: acm-health-check
